### ISSUE TITLE
[NSString length] is not equivalent to String.count

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#108]
Emojis for example may have a length different from the character count.
http://swiftify.me/7hcfop

**Comment by alex-swiftify** [comment]
@nickasd Got you.
What would you suggest?

The closest we can get is
```
print("😘".utf16.count)
```
or (uglier):
```
print(("😘" as NSString).length)
```

I would rather avoid translating `[string length]` to `string.utf16.count` by default since most users are happy with what `string.count` returns.
At best, we could make it configurable, but I'd still make `string.count` the default, given the low percentage of users who need to deal with Unicode here.

**Comment by nickasd** [comment]
I'm not an expert with encodings, but when working with text from `NSTextView` or `NSTextField` (as in my case) it may be a problem using `String.count` rather than `NSString.length`. After all, `[@"" rangeOfString:@""]` will result in `("" as NSString).range(of: "")` (returning `NSRange`), so in my case using `NSRange` and `String.count` could produce wrong results. (When dealing with strings, one should either use `Range` with `String` methods or `NSRange` with `NSString` methods, but not mix up both worlds.)
I leave it up to you.

**Comment by alex-swiftify** [comment]
I got you, @nickasd.
I wish we could use `Range` instead of `NSRange` but the generic case conversion between `NSRange` and `Range<>` is too verbose to inline.

Obviously, using `NSString.length` for most cases would cause a lot of questions from our users, too.
At most, we can make this a non-default configurable option if we get more request from the community.

With our current approach, we prefer using Swift classes (such as `String`, `URL`, etc), but for methods that can't be reliably translated to methods of Swift classes, we bridge to `NSString`, `NSRange`, etc.

At this point, I see nothing better than to close this unresolved :(
