### ISSUE TITLE
C struct memberwise initialisation turns into Swift Array

### ISSUE THREAD

**Issue by bobergj** [Swiftify-Corp/Swiftify#134]
```
@import MapKit;

/** Componentwise min */
static inline MKMapPoint NMapPointMin(MKMapPoint point1, MKMapPoint point2)
{
    MKMapPoint minPoint = { MIN(point1.x, point2.x), MIN(point1.y, point2.y) };
    return minPoint;
}
```

```
//* Componentwise min
@inline(__always) private func NMapPointMin(_ point1: MKMapPoint, _ point2: MKMapPoint) -> MKMapPoint {
    let minPoint = [min(point1.x, point2.x), min(point1.y, point2.y)] as? MKMapPoint
    return minPoint!
}
```

http://swiftify.me/ejcq31

**Comment by alex-swiftify** [comment]
@bobergj FYI, the following form is already supported, if you explicitly specify field names in Objective-C (C99) struct initializers:
```
    MKMapPoint minPoint = { .x = MIN(point1.x, point2.x), .y = MIN(point1.y, point2.y) };
```
http://swiftify.me/ejcq31/1
Also, fixed indentation for this sample - will be effective since the next converter update.

We have a task in our backlog to support such a short form of initializers:
https://swiftify.atlassian.net/browse/SWC-250
.. however, this appears to be more difficult as we will have to infer field names (i.e. `x` and `y`), which are missing in Objective-C but required in Swift.
Should be possible anyway.

**Comment by alex-swiftify** [comment]
@bobergj  Now (effective since the next update) your sample would produce the following:
```
import MapKit

//* Componentwise min

@inline(__always) private func NMapPointMin(_ point1: MKMapPoint, _ point2: MKMapPoint) -> MKMapPoint {
    let minPoint = MKMapPoint(min(point1.x, point2.x), min(point1.y, point2.y))
    return minPoint
}
```

Which is almost correct except for missing argument labels (which can be easily added via Xcode auto-fix suggestions).

We are still working on getting the necessary information to generate the field names for memberwise initializers (which are just missing in Objective-C but required in Swift).

**Comment by alex-swiftify** [comment]
@bobergj FYI, this is now fully addressed, including inference of argument labels (even if they are missing in the Objective-C code).

Converter output (will be effective since the next update):
```
import MapKit

/// Componentwise min
@inline(__always) private func NMapPointMin(_ point1: MKMapPoint, _ point2: MKMapPoint) -> MKMapPoint {
    let minPoint = MKMapPoint(x: min(point1.x, point2.x), y: min(point1.y, point2.y))
    return minPoint
}
```
