### ISSUE TITLE
NS_SWIFT_UNAVAILABLE on property parse error

### ISSUE THREAD

**Issue by bobergj** [Swiftify-Corp/Swiftify#140]
http://swiftify.me/ay0d46
```
@interface Foo : NSObject
@property (nonatomic, readonly, copy) NSString *a NS_SWIFT_UNAVAILABLE("");
@property (nonatomic, readonly, copy) NSString *b;
@end
```

Although conversion succeeds, results in multiple errors being logged.

**Comment by bobergj** [comment]
Example where NS_SWIFT_UNAVAILABLE results in incorrect/failed conversion:
http://swiftify.me/utm3zj/1

**Comment by alex-swiftify** [comment]
@bobergj 
Fixed. It will be available in the next update.
Converter output:
```
class Foo: NSObject {
    private(set) var a: String?
    private(set) var b: String?
}
```
P.S. We currently don't comment out or otherwise denote declarations marked as `NS_SWIFT_UNAVAILABLE `.
I am not sure if commenting them out will be the right thing to do in all cases, so I'm rather leaving this to the user.

Other cases from http://swiftify.me/utm3zj/1 are already fixed and deployed.
