### ISSUE TITLE
Functions in my classes are rearranged

### ISSUE THREAD

**Issue by arlomedia** [Swiftify-Corp/Swiftify#152]
After converting a class file with the Advanced Project Converter, my functions are often arranged into a different order from how I wrote them.  I'm not sure if there's a pattern to this, but it might be moving functions that aren't referenced in the class header file to the end. That would include functions overridden from a superclass (for example, viewDidLoad in a subclass of UIViewController) as well as custom functions that I just neglected to list in the header.

Anyway, I have a logic and consistency to how my functions are organized (with viewDidLoad coming first, for example) and would like to see that preserved. Currently after converting, I'm going through and copy/pasting the functions back into the original order.

I can provide a couple example files that demonstrate the problem if that's helpful.

**Comment by arlomedia** [comment]
I paid more attention to this today and indeed, it looks like functions that are not listed in the Objective C class header file are moved to the end of the resulting Swift file.

**Comment by alex-swiftify** [comment]
Thanks, @arlomedia  for reporting!

This is a know "issue", and your assumption about moving functions not listed in the Objective-C header file to the end is correct.

The converter is dealing with 2 lists of declarations (one in the header file and another one in the implementation file), and merging these lists into one.

Most methods omitted in the header file are private (however, thanks for mentioning overridden functions!).
Since most Swift style guides recommend that private declarations will go after public,
the converter outputs declarations present in the header file first, then those not present in the header file.

Do you think we should rather do the opposite? That is, use the order from the implementation (`.m`) file as the base?

If we do so, 
- declarations present in the `.h` file only (but not in the `.m` file) should be listed first.
- then we list declarations present in the `.m` file, preserving the ordering from the `.m` file.

**Comment by alex-swiftify** [comment]
P.S. Here is a related option that you may try unchecking: [Reorder top-level declarations (place static methods and global variables outside of class)](https://support.swiftify.com/hc/en-us/articles/360028372351-Reorder-top-level-declarations-place-static-methods-and-global-variables-outside-of-class-).

However, this only affects the reordering of static declarations, and I would recommend leaving this selected so that static declarations are moved outside of the class declarations (as they are converted to global functions in Swift).

Feel free to share sample files that demonstrate the problem - that would help us make the final decision.

**Comment by arlomedia** [comment]
> Do you think we should rather do the opposite? That is, use the order from the implementation (`.m`) file as the base?

That would work well for me. I don't think I have any instances of a declaration in the .h file that isn't in the .m file, so I don't know what implications that might have for others. But it seems logical since a "header" file is kind of like the "top" of the implementation file.

Another category of functions that aren't meant to be private but aren't in the .h file are functions adopted from a protocol. That gives us at these categories to deal with:

1. Functions overridden from a superclass, like init, viewDidLoad and viewWillAppear. These particular examples are all "setup" type functions and I like to keep them at the top, but then something like applicationWillResignActive might go at the bottom and other things might make sense somewhere in the middle. This would also include subclasses of my own classes, not just SDK classes.
2. Functions adopted from a protocol, like scrollViewDidScroll and gestureRecognizer:shouldReceiveTouch from the SDK. These examples are often closely related to my own functions, so I like to keep them nearby. I also commonly use a custom protocol like DocumentPickerDelegate with a function like documentPickerDidFinish to manage popup windows. In that case, I like to put the didFinish function immediately after the function that opened it.
3. Custom functions that I simply forgot to list in the header file. This is the least common and the most understandable if you don't handle it as I would want. :-) But if you are using the sequence from the .m file, then this would be taken care of, too.

I'll email you a couple classes from yesterday that were affected by this.

**Comment by alex-swiftify** [comment]
Thanks, @arlomedia !
Using the ordering from the .m file seems possible, and we will line this up.

**Comment by alex-swiftify** [comment]
@arlomedia This has been finally implemented and will make it into the next converter update in early January.
The converter now follows the ordering of `.m` files.
