### ISSUE TITLE
Sorting NSMutableArray using Sort Selector does not convert properly 

### ISSUE THREAD

**Issue by AsadAzam** [Swiftify-Corp/Swiftify#164]
Objective-C Code
```objc
[sortedCountryArray sortUsingSelector:@selector(localizedCompare:)];
```

[Generated Swift Code](https://swiftify.me/htmyvn)

```swift
sortedCountryArray = sortedCountryArray.sortedArray(using: #selector(String.localizedCompare(_:))) as? [AnyHashable] ?? sortedCountryArray
```

Expected Swift Code
```swift
(sortedCountryArray as? NSMutableArray)?.sort(comparator: {
    ($0 as! String).localizedCompare(($1 as! String))
})
```

Or simply, if we change the type of `sortedCountryArray` from `[AnyHashable]` to `[String]`; as `localizedCompare` is for `String/NSString` ([Apple Documentation](https://developer.apple.com/documentation/foundation/nsstring/1416999-localizedcompare))
```swift
sortedCountryArray = sortedCountryArray.sorted()
```

**Comment by alex-swiftify** [comment]
@AsadAzam 
You should include the declaration of `sortedCountryArray ` in the conversion for the converter to know about this variable's type: https://swiftify.me/htmyvn

The only change improvement that I have made (this will be available in the next update) is fixed the translated Swift selector name from `AnyHashable.localizedCompare(_:)` to `NSString.localizedCompare(_:)`.

Now the output is as follows (will be effective since the next converter update):
```
var sortedCountryArray: [AnyHashable] = []
sortedCountryArray = (sortedCountryArray as NSArray).sortedArray(using: #selector(NSString.localizedCompare(_:))) as? [AnyHashable] ?? sortedCountryArray
```

You suggested code looks less universal to me as it hardcodes the type name "String" when typecasting.
