### ISSUE TITLE
Incorrect selector in offline conversion

### ISSUE THREAD

**Issue by OolonColoophid** [Swiftify-Corp/Swiftify#166]
In Xcode Version 12.5 (12E262) on macOS 11.4 this:

```
BOOL dataSourceProvidesShapes = [[self dataSource] respondsToSelector:@selector(thoughtGroupView:isBackgroundShapeAtIndex:)];
```

is rendered:

```
let dataSourceProvidesShapes = dataSource?.responds(to: #selector(MPPlayableContentDataSource.thoughtGroupView(_:isBackgroundShapeAtIndex:))) ?? false
```

Cheers

Ian

**Comment by alex-swiftify** [comment]
@OolonColoophid This has been fixed.
Now we have resorted to using the `Selector()` "syntax sugar" instead of the `#selector()` keyword for such cases, when the method declaration with selector `thoughtGroupView:isBackgroundShapeAtIndex:` is not included in the current scope (thus we cannot infer the correct class name for the `#selector()` keyword.

Converter output:
```
let dataSourceProvidesShapes = dataSource?.responds(to: Selector("thoughtGroupView:isBackgroundShapeAtIndex:")) ?? false
```
