### ISSUE TITLE
Initialising NSAttributedString attributes dictionary

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#167]
Some values in the attributes dictionary can be null, using `compactMapValues` would ensure that the dictionary the type of the dictionary is `[NSAttriburedString.Key: Any]`

https://swiftify.com/converter/code/1dakzl/

**Objective-C code**

```
NSDictionary *superscriptTextAttributes = [NSDictionary dictionaryWithObjectsAndKeys:
                                               [fnt fontWithSize:superscriptCharSize], NSFontAttributeName,
                                               characterBaselineOffsetUp, NSBaselineOffsetAttributeName,
                                               nil];
// use this above if we want to add color too
// colorOfSuperText, NSForegroundColorAttributeName    

// apply them
[attributedString setAttributes:superscriptTextAttributes range:positionOfSuperscriptCharacter];
```

**Converted Swift Code**

```
let superscriptTextAttributes = [
    .font : fnt.withSize(superscriptCharSize),
    .baselineOffset : characterBaselineOffsetUp
]
// use this above if we want to add color too
// colorOfSuperText, NSForegroundColorAttributeName

// apply them
attributedString.setAttributes(superscriptTextAttributes as? [NSAttributedString.Key : Any], range: positionOfSuperscriptCharacter)
```

**Suggested Converter Output**

```
let superscriptTextAttributes = [
    NSAttributedString.Key.font : fnt?.withSize(CGFloat(superscriptCharSize)),
    NSAttributedString.Key.baselineOffset : characterBaselineOffsetUp
].compactMapValues { $0 }
// use this above if we want to add color too
// colorOfSuperText, NSForegroundColorAttributeName
 
// apply them
attributedString?.setAttributes(superscriptTextAttributes, range: positionOfSuperscriptCharacter)

```

**Comment by alex-swiftify** [comment]
@Ibrahimhass I have changed the output to explicitly include `NSAttributedString.Key.` type qualifiers.

Current output:
```
let superscriptTextAttributes: [AnyHashable : Any]? = [
    NSAttributedString.Key.font : fnt.withSize(superscriptCharSize),
    NSAttributedString.Key.baselineOffset : characterBaselineOffsetUp
]

attributedString.setAttributes(superscriptTextAttributes as? [NSAttributedString.Key : Any], range: positionOfSuperscriptCharacter)
```

Regarding the addition of `.compactMapValues`, I have tried several approaches but I cannot find a universal approach to follow:
1) Adding `.compactMapValues { 0 }` to any dictionary initializer in the converted code seems redundant, and does not exactly follow the behavior of `dictionaryWithObjectsAndKeys:` like initializer methods.
2) Adding `.compactMapValues { 0 }` to the first argument of the `setAttributes()` method call won't solve the compilation problem because the dictionary type still cannot be determined.
3) Explicitly specifying the dictionary type as `let superscriptTextAttributes: [AnyHashable : Any] = <...>` is not very desirable, since this prevents Xcode from inferring the actual dictionary type.
4) Detecting the exact dictionary type as `let superscriptTextAttributes: [NSAttributedString.Key : Any] = <...>` requires quite a large amount of work and testing, this will help only with `dictionaryWithObjectsAndKeys:` and `initWithObjectsAndKeys:` methods.

I don't see an easy (or even worthwhile) fix here, unfortunately.

Below is the code for (3), which I decided not to include.
```
            MessageExpressionContext messageExpression = Initializer?.expression().GetNestedMessageExpression();
            
            if (messageExpression != null
                && Converter.MessageAccessor.GetMessageSelectorName(messageExpression.messageSelector())
                    .EqualsAny(DictionaryInitializerBuilder.DictionaryInitializerMethods))
            {
                return false;
            }
```
