### ISSUE TITLE
Skip converting unimplemented header method declarations (returning a value)

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#168]
**Suggested Change**
Do not convert methods that do not have an implementation but are declared in the header.
https://swiftify.me/jyeh8o

**Objective-C code**
```
#import <Foundation/Foundation.h>

@interface TestClass : NSObject

- (NSAttributedString *)superscriptMethod3;
- (NSAttributedString *)method3;
- (NSAttributedString *)method4;

@end

#import "TestClass.h"

@interface TestClass ()

@end

@implementation TestClass

@end

```

**Converted Swift Code**
```
import Foundation

class TestClass: NSObject {
    func superscriptMethod3() -> NSAttributedString? {
    }

    func method3() -> NSAttributedString? {
    }

    func method4() -> NSAttributedString? {
    }
}
```

**Suggested Change**

```
import Foundation

class TestClass: NSObject {

}

```

**Comment by alex-swiftify** [comment]
@Ibrahimhass What's the rationale to make this change?

Here is [how Xcode imports such an Objective-C code](https://share.getcloudapp.com/NQuoQEo6).

Many times Swiftify users insisted that any piece of code that was included in Objective-C would be preserved in the Swift version.
If the code is unused, that's up to the developer to clean up the code after the conversion.

**Comment by Ibrahimhass** [comment]
@alex-swiftify this increases the number of errors as for functions or methods with no return type even if they are unimplemented it does not cause an error in Xcode. I understand that it is up to the user to clean up the code after conversion so in this case, a better solution could be to comment before the function/method like

```
import Foundation

class TestClass: NSObject {
     // unimplemented 
    func superscriptMethod3() -> NSAttributedString? {
    }

     // not implemented 
    func method3() -> NSAttributedString? {
    }

     // missing original implemetation
    func method4() -> NSAttributedString? {
    }
}
```

**Comment by alex-swiftify** [comment]
@Ibrahimhass I got your suggestion.
However, we had many cases when our users were blaming us for removing anything from the original code.

The fact that output code will likely produce compiler errors is good since this forces the user to review and remove the code.
Same time, these methods might be required by a category/protocol/superclass, and silently removing them may not be desirable.
This is, nevertheless, something for the user to review after the conversion, and compiler warnings will hint them about that.

We could add `// WARN:` tokens to such a code but I can't justify this either.
Users converting just a plain header file separately from the implementation file will get a lot of such `// WARN:` comments which also may not be desirable.
