### ISSUE TITLE
ObjC conditional compilation with #if

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#175]
**Objective-C code**

```
#if MYW_TARGET_MAIN
if (!needToSkipInter) {
    [InterManager.shared activate:EventTypeBookmarksClosed];
}
#endif
[AlertUpdateManager.shared markAllAlertsAsViewed];

```
https://swiftify.me/7x44sw
**Converted Swift Code**

```
if MYW_TARGET_MAIN {
if !needToSkipInter {
    InterManager.shared.activate(EventTypeBookmarksClosed)
}
}
AlertUpdateManager.shared.markAllAlertsAsViewed()
```

**Expected Swift Code**
```
#if MYW_TARGET_MAIN 
if !needToSkipInter {
    InterManager.shared.activate(EventTypeBookmarksClosed)
}
#endif
AlertUpdateManager.shared.markAllAlertsAsViewed()
```

**Comment by alex-swiftify** [comment]
Interesting question.

I. We do translate `#define` to `let`, and `#if` ... `#endif` to `if {}` blocks: https://swiftify.me/ctesgs
because:
1) Xcode [imports `#define` as a `let` constant](https://share.getcloudapp.com/jkuPke81).
2) Swift does not support complex conditions in conditional `#if` expressions, only basic `&&` and `||` operators are supported.

However, I see the following reasons to keep `#if` ... `#endif` directives in Swift:
1) Most [Stack Overflow suggestions](https://stackoverflow.com/questions/24003291/ifdef-replacement-in-the-swift-language) advise using `#if` ... `#endif` directives and defining "Active Compilation Conditions" in Xcode.
2) Swift 5.5's SE-0308 proposal allows Swift to use `#if` conditions with postfix member expressions

II. **Related note**. If we change this to keep `#if` ... `#endif` directives in Swift, that's questionable whether we should translate 
`#define MYW_TARGET_MAIN 1`
to
(a) `let MYW_TARGET_MAIN = 1` (as in Xcode), or 
(b) `//#define MYW_TARGET_MAIN 1` (a commented out define)

I still think that (a) is a better option because this is how we translate other `#define` statements ([example](https://swiftify.me/uza479)).

The reason why we have changed the translation of `#if` .. `#endif` directives in https://swiftify.atlassian.net/browse/SWC-856 was this customer's report:

> Even though the "#define ASDF" has been converted to "let ASDF", "#if ASDF" is not converted.

@Ibrahimhass @tomattoz @nickasd Your votes are welcome here.

**Comment by alex-swiftify** [comment]
@Ibrahimhass What's your opinion on this one?

**Comment by Ibrahimhass** [comment]
@alex-swiftify 

> II. Related note. If we change this to keep #if ... #endif directives in Swift, that's questionable whether we should translate
#define MYW_TARGET_MAIN 1
to
(a) let MYW_TARGET_MAIN = 1 (as in Xcode), or
(b) //#define MYW_TARGET_MAIN 1 (a commented out define)
>I still think that (a) is a better option because this is how we translate other #define statements (example).

I think we should convert the `#define` to `let MYW_TARGET_MAIN = 1` (as in Xcode)

And we should keep support `#if` in Swift. 
Even though it seems a bit inconsistent.

**Comment by alex-swiftify** [comment]
Thanks, @Ibrahimhass - I have the same in mind.
I will line up those changes.

**Comment by alex-swiftify** [comment]
I'm closing this out and keeping the corresponding JIRA issue open - https://swiftify.atlassian.net/browse/SWC-1154.
