### ISSUE TITLE
Configure Bridging Header not working

### ISSUE THREAD

**Issue by acarioni** [Swiftify-Corp/Swiftify#179]
I'm trying to convert an Objective-C project with Swiftify for Xcode 5.4 (155) running in Xcode 12.5.1 (12E507). As the first step I call Configure Bridging Header. The configuration runs fine but the project doesn't compile anymore. Xcode complains that the file "MyProject-Swift.h", imported in "MyProject_Prefix.pch", doesn't exist.

**Comment by alex-swiftify** [comment]
Hi @acarioni,

Thanks for reporting!

The [Swift Bridging Header file](https://support.swiftify.com/hc/en-us/articles/360015696152-Update-Bridging-Header-and-PCH-files) is automatically created by Xcode (rather than Swiftify), only if your project compiles successfully and contains at least one Objective-C and one Swift file.

So, the solution should be as follows:

1. Comment out `#import "MyProject_Prefix.pch"` in the PCH file.
2. Ensure that your project contains at least one Objective-C file and one Swift file.
For this purpose, Swiftify usually creates an empty "MyProject_Prefix.swift" file once you press the "Configure Bridging Header" button.
Once your project has one or more "real" Swift files, "MyProject_Prefix.swift" can be safely deleted.
3. Ensure that the project builds successfully.
4. See if the "MyProject-Swift.h" file has been generated (by Xcode).
5. Uncomment the import and build the project again.

I hope this helps. Let me know if you have more questions.
