### ISSUE TITLE
Obj-C to Swift 4.1 conversion fails with confusing (to me) error message

### ISSUE THREAD

**Issue by frameworker** [Swiftify-Corp/Swiftify#2]
Obj-C to Swift 4.1 conversion fails with confusing (to me) error message

Obj-C input:
[self.label drawInRect: destRect withAttributes: @{NSFontAttributeName: [NSFont boldSystemFontOfSize: 36.0]}];

Swift 4.1 output:
label?.draw(in: destRect, withAttributes: [NSAttributedStringKey.font: NSFont.boldSystemFont(ofSize: 36.0)])

Error message in Xcode 9.2:
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'

**Comment by alex-swiftify** [comment]
Hi,

`NSAttributedStringKey.font` was introduced since iOS11 and macOS 10.13:
https://developer.apple.com/documentation/foundation/nsattributedstring/key

If you target an older version of iOS or macOS, replace `NSAttributedStringKey.font` with `NSFontAttributeName`.
See https://stackoverflow.com/questions/46966681/nsfontattributename-vs-nsattributedstringkey-font
for more details around this.

Currently, we do not have an option to generate different code depending on the target iOS version,
and we have recently switched to generate iOS11+ compatible code for `NSAttributedStringKey` and few related enumerations.

If you have any better suggestions to handle this, you are welcome!

**Comment by frameworker** [comment]
Thank you, Alex-swiftly! That explains the root of my issue. Appreciatively, @joely
