### ISSUE TITLE
Incorrect property conversion 

### ISSUE THREAD

**Issue by dhoerl** [Swiftify-Corp/Swiftify#219]
//  Converted to Swift 5.6 by Swiftify v5.6.21858

Objc:

- (NSMutableArray<NSDictionary *> *)phones {
    if (!_phones) {
        _phones = [@[@{}] mutableCopy];
    }
    return _phones;
}

Swift:
    private var _phones: [[AnyHashable : Any]]?
    var phones: [[AnyHashable : Any]]? {  
        if !_phones {  <--------------------------------- should be if _phones == nil
            _phones = [[:]]
        }
        return _phones
    }

**Comment by alex-swiftify** [comment]
@dhoerl This behavior is actually "by design".

Since your code doesn't contain the declaration of  `_phones`, the converter cannot infer this variable's type.
_(It could be possible to infer the type from its usages, but we currently do not do so - it's difficult)._
If you include the declaration of `_phones`, the output will match your expectations: https://swiftify.me/zv0zs0

Also refer to [this FAQ article](https://support.swiftify.com/hc/en-us/articles/360000669752).

I'm marking this ticket as closed but let me know if you have more questions or suggestions.
