### ISSUE TITLE
Wrong conversion of addGestureRecognizer to add

### ISSUE THREAD

**Issue by AlexanderJ** [Swiftify-Corp/Swiftify#221]
With the following code I get this conversion error:
https://swiftify.me/4hjyoe

If I just use the awakeFromNib method everything is fine.

**Comment by alex-swiftify** [comment]
We follow the same "[omit needless words](https://github.com/apple/swift/blob/main/docs/CToSwiftNameTranslation-OmitNeedlessWords.md)" algorithm as Apple has introduced in Swift 3 to process method names.

Just checked, and Xcode imports this method in exactly the same way: https://take.ms/yWhg6

Easy fix: include the header file in the same conversion, so that the converter is aware of the type name: https://swiftify.me/xyseib

As an improvement, I've increased the priority of https://swiftify.atlassian.net/browse/SWC-441 to make this "Omit Needless Words" behavior configurable in the Preferences dialog.
