### ISSUE TITLE
#ifdebug #endif blocks confuse Swiftify - interface declarations

### ISSUE THREAD

**Issue by emish** [Swiftify-Corp/Swiftify#230]
The following example yields an error. 

Sample: 
```
#if DEBUG || DEBUG_MENU


@interface Foo () <BarOne, BarTwo>

#else


@interface Foo () <BarOne, BarThree>
#endif
```

The error is
```
Foo.m: (161:0) Extraneous input '@interface'
Foo.m: (161:34) Mismatched input '<'
```

Where line 160 is the `#endif`.

**Comment by alex-swiftify** [comment]
@emish 

> Option 4 seems like an easy way to address this if you don't need an entire project to compile the single file. 

I'm not 100% sure if I understood you correctly.
I was meaning to invoke the preprocessor on the file, rather than compile it.
If you mean that some #include directives in the file won't allow to preprocess it - we can find a way to ignore #include directives.

Or, did you mean that the result of the preprocessing will be useless to you since it will be missing all conditional branches?
