### ISSUE TITLE
not generating fallthrough in switch statements

### ISSUE THREAD

**Issue by rob-miller** [Swiftify-Corp/Swiftify#243]
Most of the switch statements in [voFunction.m](https://github.com/rob-miller/rTracker/blob/master/Classes/voFunction.m) make use of falling through to subsequent `case:` labels, however only one Swift `fallthrough` statement was generated in the entire Swiftify output file.  There are no mentions of the file in the ConversionLog.txt file.

Here's a snipped example where the one (ot enough) fallthrough was generated:

Objective-C:

                        switch (currTok) {
                            case FN1ARGELAPSEDWEEKS:
                                result /= d(7);
                            case FN1ARGELAPSEDDAYS:
                                result /= d(24);
                            case FN1ARGELAPSEDHOURS:
                                result /= d(60);
                            case FN1ARGELAPSEDMINS:
                                result /= d(60);
                            case FN1ARGELAPSEDSECS:
                            default:
                                break;
                        }
Swiftify:

                        switch currTok {
                        case FN1ARGELAPSEDWEEKS:
                            result /= d(7)
                        case FN1ARGELAPSEDDAYS:
                            result /= d(24)
                        case FN1ARGELAPSEDHOURS:
                            result /= d(60)
                        case FN1ARGELAPSEDMINS:
                            result /= d(60)
                        case FN1ARGELAPSEDSECS:
                            fallthrough
                        default:
                            break
                        }

for reference, the surrounding code can be seen [here](https://github.com/rob-miller/rTracker/blob/0ec6cf2a268946dc957982f7d3db01a8a1272a52/Classes/voFunction.m#L555-L567)

**Comment by alex-swiftify** [comment]
@rob-miller You have specified a sample that (seemingly correctly) generates `fallthrough` statements, 
but I cannot find a case which is incorrect based off your suggested code samples and the file.

When a few case labels are handled by the same code, Swiftify groups those case labels as you can see [here](https://swiftify.me/4m994r).

When a case label and the `default` statement are handled by the same code, we need to generate the `fallthrough` statement, because Swift doesn't support something like this:
```
                    case FN1ARGELAPSEDSECS, default:
                        break
```

Can you provide a sample that generates a "wrong" code (or at least point to such code in the source file that you provided)?

**Comment by rob-miller** [comment]
Perhaps this has been fixed since March 2023 when Swiftify was run on my project?  The code in my post above is copied from the files I received, but I can't find any relevant closed GitHub issue.

[voFunction.swift.zip](https://github.com/Swiftify-Corp/Swiftify/files/12753681/voFunction.swift.zip)

**Comment by alex-swiftify** [comment]
@rob-miller I cannot recall any changes to the ‘fallthrough” behaviour recently so it’s very unlikely that this has been fixed since March 2023. 
Can you point to the line in the Swift output that you find wrong?
Because in the ticket’s summary there’s the sample which *does* include a fallthrough statement, so I can’t see anything wrong so far. 

If needed, I can grant you temporarily free access to Swiftify for testing, or you can use the Xcode extension that allows 3 free code conversions per day to reproduce it. 

Thanks again for your help with these reports!

**Comment by rob-miller** [comment]
The problem is that in the generated sample code there is only one fallthrough statement.  The calculation shown is processing a value to get it to 'per seconds'.  If the token indicates the value is for weeks, divide by 7 and carry on processing as if it were for days, then for hours etc.  

So I think the Swiftify output should be:

                        switch currTok {
                        case FN1ARGELAPSEDWEEKS:
                            result /= d(7)
                            fallthrough
                        case FN1ARGELAPSEDDAYS:
                            result /= d(24)
                            fallthrough
                        case FN1ARGELAPSEDHOURS:
                            result /= d(60)
                            fallthrough
                        case FN1ARGELAPSEDMINS:
                            result /= d(60)
                            fallthrough
                        case FN1ARGELAPSEDSECS:
                            fallthrough
                        default:
                            break
                        }

**Comment by alex-swiftify** [comment]
@rob-miller Thanks for explaining the things, and sorry for my ignorance!
Everything makes perfect sense to me now.
Will be addressed for sure.

**Comment by alex-swiftify** [comment]
Fixed (will be available in the next converter update).

Converter output (for the case in the Summary):
```
switch currTok {
case FN1ARGELAPSEDWEEKS:
    result /= d(7)
    fallthrough
case FN1ARGELAPSEDDAYS:
    result /= d(24)
    fallthrough
case FN1ARGELAPSEDHOURS:
    result /= d(60)
    fallthrough
case FN1ARGELAPSEDMINS:
    result /= d(60)
    fallthrough
case FN1ARGELAPSEDSECS:
    fallthrough
default:
    break
}
```
