### ISSUE TITLE
Unnecessary initialization of method parameter to itself

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#52]
When a method parameter is reassigned, the `var` declaration can be merged with the initialization.
http://swiftify.me/l4iyzz

**Comment by alex-swiftify** [comment]
@nickasd While I agree this is desirable, we follow a common pattern as suggested [here](https://stackoverflow.com/a/36165146/1531236).

Merging the `var` may be desirable but it's not an easy task for the converter considering all side-effects.
I have to close this as "won't fix" since our output would still compile.
