### ISSUE TITLE
NSFileHandlingPanelCancelButton

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#58]
Instead of doing `openPanel.runModal().rawValue == NSFileHandlingPanelCancelButton`, this would suffice: `openPanel.runModal() == .cancel`.
http://swiftify.me/0uwyg3

**Comment by tomattoz** [comment]
I've mapped NSFileHandlingPanelOKButton to NSApplication.ModalResponse.OK and NSFileHandlingPanelCancelButton to NSApplication.ModalResponse.cancel. But in your example it still will be conversion to NSUInteger because NSApplication.ModalResponse is struct.

But for now we doesn't support structs shortening, task: https://swiftify.atlassian.net/browse/SWC-1047.

**Comment by alex-swiftify** [comment]
Fixed.

Input:
```
if ([NSOpenPanel.openPanel runModal] == NSFileHandlingPanelOKButton) {
    NSLog(@"well done");
}
```

Output:
```
if NSOpenPanel().runModal() == .OK {
    print("well done")
}
```
