### ISSUE TITLE
[NSIndexSet countOfIndexesInRange:]

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#84]
Could be improved to `IndexSet.count(in:)`.
http://swiftify.me/sixnvq

**Comment by alex-swiftify** [comment]
@nickasd I wish we could use `IndexSet.count(in:)` but the latter method accepts a `Range<Index>` parameter rather than `NSRange`.
Since the conversion from `NSRange` to `Range<Index>` is possible but very verbose to inline (see https://stackoverflow.com/a/30404532/1531236), we have resorted to using NSXXX methods (i.e. NSIndexSet, NSString, etc) for methods that accept `NSRange` as a parameter.

For your particular case, we could translate `NSMakeRange` to `Range<String.Index>(start: 0, end: 0)`, however, I don't see any generic solution here, i.e. if a range was passed as a variable:
```
[indexes countOfIndexesInRange:myRange];
```

If you see any universal translation for this, you are welcome!
