### ISSUE TITLE
Incorrect "Skipping redundant initializing to itself"

### ISSUE THREAD

**Issue by bvirlet** [Swiftify-Corp/Swiftify#95]
http://swiftify.me/b64hlr

Could be related to #26 ?

This resulted in really broken code. I'd rather keep redundant initialization rather than generate incorrect code.

**Comment by alex-swiftify** [comment]
Thanks, Bruno for reporting!

The "real" underlying issue is our logic for skipping `self` prefixes.
At least when the property declaration is included: http://swiftify.me/2aixcz/2
we should keep the `self.` prefix.
If the `self.` prefix is kept, which makes the lvalue different from rvalue, 
this won't be commented out in the output.

If the lvalue is indeed the same as rvalue, I see nothing bad in commenting out the assignment it it really does nothing.

**Comment by bvirlet** [comment]
Are there really cases where the lvalue and rvalue are the same?

**Comment by alex-swiftify** [comment]
@bvirlet I had to dig into our code and unit tests to find out.

See the following sample (a bit tricky one):
http://swiftify.me/av87be

1) The first `var attributes = attributes` line is added by the converter to create a shadow variable, thus making the `attributes` parameter writable;
2) The line `attributes = [attributes mutableCopy];` translates to `attributes = attributes` and we have a logic to skip that. Otherwise, the result will look like follows:
```
func test(_ attributes: [AnyHashable : Any]?) {
    var attributes = attributes
    attributes = attributes
}
```

**Comment by alex-swiftify** [comment]
Fixed (will be available in the next update). Output:

```
class Object {
    var products: [SKProduct] = []

    func viewDidLoad() {
        Store.shared.products(onSuccess: { products in
            if let products = products {
                self.products = products
            }
            self.tableView.reloadData()
        })
    }
}
```
Note: the `products` property gets translated to a non-optional array (`[]`) to avoid introducing an optional property. This is "by design" in the current version of the converter.
Same time, `products` block parameter gets translated to an optional array (`[]?`).
Thus we need to unwrap `products` with an `if let` statement.
