### ISSUE TITLE
Error in AppCode

### ISSUE THREAD

**Issue by firetrap** [Swiftify-Corp/Swiftify#96]
I'm trying your appCode plugin with a free key but everytime when i select a *.h and the *.m file to convert it gives me: Swiftify: No converted content received from server.

**Comment by alex-swiftify** [comment]
Hi there,

Thanks for reporting!
Could you narrow this down to a single .h or .m file and send it for troubleshooting?

You can share the file privately at alex@swiftify.com
Thanks in advance!

**Comment by AlexUdalov** [comment]
https://swiftify.atlassian.net/browse/SWE-369

**Comment by alex-swiftify** [comment]
Hi there,

Just wanted to follow-up on this issue.
Since we have revisited conversion of files in our whole solution, and the AppCode plugin now allows conversion of multiple `.h` and `.m` files, this feature is now included only for a [Pro and Unlimited plans](https://objectivec2swift.com/#/pricing).

The "Convert Selection" command can be still used for free, even when selecting a whole file.

Previously, the "Convert File ..." command was able to handle only a single file, and essentially worked the same way as "Convert Selection" when you select the whole file.

With the new behavior (which supports joining `.h` and `m` files into `.swift` output), the "Convert File(s) to Swift" command requires backend method that support conversion of files, and they are just unavailable for free plan users.

We are going to update the error message in the AppCode plugin to accommodate this change ASAP.

**Comment by alex-swiftify** [comment]
This has been addressed in the version 5.0.2 currently pending approval in the JetBrains plugin repository.
Thanks again for reporting!
